title: At The Mile Documentation
description: Docs for internally hosted At The Mile projects.
theme: just-the-docs
color_scheme: dark

url: https://at-the-mile.github.io


callouts_level: loud
callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  wip:
    title: Work-in-Progress
    color: yellow